// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sqlite_models.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "sqlite_models.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace org {
namespace yaorm {
namespace sqlite {

namespace protobuf_sqlite_5fmodels_2eproto {


namespace {

const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[1] = {};
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;
namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "sqlite_models.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      NULL, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\023sqlite_models.proto\022\020org.yaorm.sqlite*"
      "H\n\nSQLiteType\022\017\n\013SQLITE_NONE\020\000\022\010\n\004TEXT\020\001"
      "\022\013\n\007INTEGER\020\002\022\010\n\004REAL\020\003\022\010\n\004BLOB\020\004*\344\001\n\021SQ"
      "LiteTypeMapping\022\027\n\023SQLITE_MAPPING_NONE\020\000"
      "\022\n\n\006DOUBLE\020\003\022\t\n\005FLOAT\020\003\022\t\n\005INT32\020\002\022\t\n\005IN"
      "T64\020\002\022\n\n\006UINT32\020\002\022\n\n\006UINT64\020\002\022\n\n\006SINT32\020"
      "\002\022\n\n\006SINT64\020\002\022\013\n\007FIXED32\020\002\022\013\n\007FIXED64\020\002\022"
      "\014\n\010SFIXED32\020\002\022\014\n\010SFIXED64\020\002\022\010\n\004BOOL\020\002\022\n\n"
      "\006STRING\020\001\022\t\n\005BYTES\020\004\032\002\020\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 352);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "sqlite_models.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_sqlite_5fmodels_2eproto

const ::google::protobuf::EnumDescriptor* SQLiteType_descriptor() {
  protobuf_sqlite_5fmodels_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_sqlite_5fmodels_2eproto::file_level_enum_descriptors[0];
}
bool SQLiteType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* SQLiteTypeMapping_descriptor() {
  protobuf_sqlite_5fmodels_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_sqlite_5fmodels_2eproto::file_level_enum_descriptors[1];
}
bool SQLiteTypeMapping_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace sqlite
}  // namespace yaorm
}  // namespace org

// @@protoc_insertion_point(global_scope)
